#!/usr/bin/env python3

import swayutils

prev_ws_num = swayutils.prev_workspace_for_current_output_num()
cmd = f"move container to workspace {prev_ws_num}; workspace {prev_ws_num}"
swayutils.command(cmd)
