#!/usr/bin/env zsh
if [[ "$HOST" == "kyogre" ]]; then
    feh --no-fehbg --bg-fill "$HOME/.config/wallpapers/wallpaper_left" "$HOME/.config/wallpapers/wallpaper_right"
elif [[ "$HOST" == "darkrai" ]]; then
    feh --no-fehbg --bg-fill "$HOME/.config/wallpapers/wallpaper"
fi
