#!/usr/bin/env zsh

UPDATEFILE="$HOME/.lastupdate"

# update nvim
echo "Updating nvim"
nvim -es -i NONE -c "PlugUpgrade" -c "PlugUpdate" -c "CocUpdate"

# update tmux plugins
echo "Updating tmux plugins"
$HOME/.config/tmux/plugins/tpm/bin/update_plugins all

# update prezto
echo "Updating prezto"
git -C $HOME/.config/prezto pull
git -C $HOME/.config/prezto submodule update --init

# check for system updates
echo "Checking for system updates"
checkupdates >/dev/null
if [ $? -eq 2 ]; then
    echo "No system updates available"
    touch "$UPDATEFILE"
elif [ $? -eq 0 ]; then
    read REPLY\?"System updates are available. Would you like to update now? [y/N] "
    REPLY=$(echo "$REPLY" | tr '[:upper:]' '[:lower:]')
    if [ "${REPLY}" = "y" ]; then
        echo "Updating"
        yay -Syu
        touch "$UPDATEFILE"
    elif [ "${REPLY}" = "n" ] || [ "${REPLY}" = "" ]; then
        :
    else
        echo "Unknown input"
    fi
else
    echo "Error in checkupdates"
fi
