#!/usr/bin/env zsh

# needed for udev
sleep 1

xsetwacom set "HID 256c:006d Pen stylus" Mode Absolute
xsetwacom set "HID 256c:006d Pen stylus" Rotate ccw
# right half of ultrawide screen
xsetwacom set "HID 256c:006d Pen stylus" MapToOutput "1280x1080+1280+0"
xsetwacom set "HID 256c:006d Pen stylus" Area "0 0 37630 31750"
